package mvc.view.centralApp;

import javax.swing.*;
import java.awt.*;

public class ViewDeleteDepartment extends JFrame
{
    private JLabel msgLabel;
    private JButton okButton;
    private JButton cancelButton;
    private JLabel headerLabel;
    private JCheckBox moveEmployeesToDepartmentCheckBox;
    private JComboBox departmentComboBox;
    private JPanel deleteDepartmentPanel;
    private JLabel warningMsgLabel;
    private JLabel warningHeaderLabel;
    private JLabel noOtherDepartmentLabel;

    /* CONSTRUCTOR */

    public ViewDeleteDepartment()
    {
        setSize(600, 250);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        add(deleteDepartmentPanel);
        setVisible(true);
    }

    /* GETTER */

    public JLabel getMsgLabel()
    {
        return this.msgLabel;
    }

    public JCheckBox getMoveEmployeesToDepartmentCheckBox()
    {
        return this.moveEmployeesToDepartmentCheckBox;
    }

    public JComboBox getDepartmentComboBox()
    {
        return this.departmentComboBox;
    }

    public JLabel getWarningHeaderLabel()
    {
        return this.warningHeaderLabel;
    }

    public JLabel getWarningMsgLabel()
    {
        return this.warningMsgLabel;
    }

    public JLabel getNoOtherDepartmentLabel()
    {
        return this.noOtherDepartmentLabel;
    }

    public JButton getOkButton()
    {
        return this.okButton;
    }

    public JButton getCancelButton()
    {
        return this.cancelButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        deleteDepartmentPanel = new JPanel();
        deleteDepartmentPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        deleteDepartmentPanel.add(panel1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(spacer2, gbc);
        moveEmployeesToDepartmentCheckBox = new JCheckBox();
        Font moveEmployeesToDepartmentCheckBoxFont = this.$$$getFont$$$(null, Font.PLAIN, -1, moveEmployeesToDepartmentCheckBox.getFont());
        if (moveEmployeesToDepartmentCheckBoxFont != null)
            moveEmployeesToDepartmentCheckBox.setFont(moveEmployeesToDepartmentCheckBoxFont);
        moveEmployeesToDepartmentCheckBox.setSelected(true);
        moveEmployeesToDepartmentCheckBox.setText("Move employees to department :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(moveEmployeesToDepartmentCheckBox, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(spacer3, gbc);
        departmentComboBox = new JComboBox();
        Font departmentComboBoxFont = this.$$$getFont$$$(null, Font.PLAIN, -1, departmentComboBox.getFont());
        if (departmentComboBoxFont != null) departmentComboBox.setFont(departmentComboBoxFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(departmentComboBox, gbc);
        headerLabel = new JLabel();
        Font headerLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, headerLabel.getFont());
        if (headerLabelFont != null) headerLabel.setFont(headerLabelFont);
        headerLabel.setText("Delete department ?");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        panel1.add(headerLabel, gbc);
        msgLabel = new JLabel();
        Font msgLabelFont = this.$$$getFont$$$(null, Font.PLAIN, -1, msgLabel.getFont());
        if (msgLabelFont != null) msgLabel.setFont(msgLabelFont);
        msgLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        panel1.add(msgLabel, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        deleteDepartmentPanel.add(panel2, gbc);
        warningHeaderLabel = new JLabel();
        warningHeaderLabel.setText("Warning :");
        warningHeaderLabel.setVisible(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        panel2.add(warningHeaderLabel, gbc);
        warningMsgLabel = new JLabel();
        warningMsgLabel.setEnabled(true);
        Font warningMsgLabelFont = this.$$$getFont$$$(null, Font.PLAIN, -1, warningMsgLabel.getFont());
        if (warningMsgLabelFont != null) warningMsgLabel.setFont(warningMsgLabelFont);
        warningMsgLabel.setText("If you don't move the employees to another department, they will be deleted from the company.");
        warningMsgLabel.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        panel2.add(warningMsgLabel, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(spacer4, gbc);
        noOtherDepartmentLabel = new JLabel();
        Font noOtherDepartmentLabelFont = this.$$$getFont$$$(null, Font.PLAIN, -1, noOtherDepartmentLabel.getFont());
        if (noOtherDepartmentLabelFont != null) noOtherDepartmentLabel.setFont(noOtherDepartmentLabelFont);
        noOtherDepartmentLabel.setText("There is no other department available.");
        noOtherDepartmentLabel.setVisible(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        panel2.add(noOtherDepartmentLabel, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        deleteDepartmentPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 3;
        gbc.fill = GridBagConstraints.BOTH;
        deleteDepartmentPanel.add(spacer6, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        deleteDepartmentPanel.add(panel3, gbc);
        okButton = new JButton();
        okButton.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(okButton, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer7, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(cancelButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont)
    {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {resultName = currentFont.getName();}
        else
        {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {resultName = fontName;}
            else {resultName = currentFont.getName();}
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return deleteDepartmentPanel;
    }

}
